version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Update Python dependencies
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
