version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_minio_data: {}

services:
  django:
    image: ghcr.io/humanrightswatch/vhs:main
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "80:5000"
    command: /start

  postgres:
    image: postgres:14.1
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z

  worker:
    image: ghcr.io/humanrightswatch/vhs:main
    depends_on:
      - redis
      - postgres
      - minio
    ports: []
    command: /start-worker

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z.hotfix.e6c50dc4c
    volumes:
      - production_minio_data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:6
