version: '3'

services:
  django:
    image: ghcr.io/humanrightswatch/vhs:nightly
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "80:5000"
    command: /start

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${WEBAPP_STORAGE_HOME}/postgres_data:/var/lib/postgresql/data:Z
      - ${WEBAPP_STORAGE_HOME}/postgres_data_backups:/backups:z

  worker:
    image: ghcr.io/humanrightswatch/vhs:nightly
    restart: always
    depends_on:
      - redis
      - postgres
      - minio
    ports: []
    command: /start-worker

  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/minio_data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:6
    restart: always
