version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_minio_data: {}

services:
  django:
    build: &django
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: video_downloading_platform_production_django
    depends_on:
      - postgres
      - redis
      - minio
      - elasticsearch
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: video_downloading_platform_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  worker:
    <<: *django
    image: youtube_dl_web_production_worker
    depends_on:
      - redis
      - postgres
      - minio
      - elasticsearch
    ports: []
    command: /start-worker

  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z.hotfix.e6c50dc4c
    volumes:
      - production_minio_data:/data
    env_file:
      - ./.envs/.production/.django
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - discovery.type='single-node'
      - xpack.security.enabled='false'
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: video_downloading_platform_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:6
