# Generated by Django 3.1.13 on 2021-11-24 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of your download batch.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of your download batch.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of your download batch.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('name', models.TextField(blank=True, help_text='Give a meaningful name to your download batch. (Optional)', max_length=512, null=True)),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns the current download batch.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the current download request.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of the current download request.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of the current download request.')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('POST_PROCESSING', 'Post processing'), ('SUCCEEDED', 'Succeeded'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=16)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('WEP_PAGE', 'Web page')], default='VIDEO', editable=False, max_length=16)),
                ('url', models.URLField(help_text='The URL of the video to download.')),
                ('batch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='core.batch')),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns the current download request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the current downloaded content.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of the current downloaded content.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of the current downloaded content.')),
                ('in_error', models.BooleanField(default=False, editable=False)),
                ('content', models.FileField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns the current download request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
