# Generated by Django 3.1.13 on 2021-11-24 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedcontent',
            name='in_error',
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='post_processing_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='sha256',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DownloadReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the current downloaded content.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of the current downloaded content.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Latest modification of the current downloaded content.')),
                ('in_error', models.BooleanField(default=False, editable=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('download_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.downloadrequest')),
                ('owner', models.ForeignKey(editable=False, help_text='Who owns the current download request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
