# Generated by Django 3.1.13 on 2021-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default='earth-happy-neptune-kilo', help_text='Give a meaningful name to your download batch. (Optional)', max_length=512),
        ),
    ]
