# Generated by Django 3.1.13 on 2021-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211124_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default='nineteen-harry-tennis-east', help_text='Give a meaningful name to your download batch. (Optional)', max_length=512),
        ),
    ]
