# Generated by Django 3.1.13 on 2021-11-24 19:06

from django.db import migrations, models
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211124_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default=video_downloading_platform.core.models._generate_random_name, help_text='Give a meaningful name to your download batch. (Optional)', max_length=512),
        ),
    ]
