# Generated by Django 3.1.13 on 2021-11-24 19:43

from django.db import migrations, models
import django.db.models.deletion
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211124_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, help_text='Say a bit more about it. (Optional)', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default=video_downloading_platform.core.models._generate_random_name, help_text='Give a meaningful name to your download batch.', max_length=512),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='core.batch'),
        ),
    ]
