# Generated by Django 3.1.13 on 2021-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211124_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(default='No description', help_text='Say a bit more about it. (Optional)'),
        ),
    ]
