# Generated by Django 3.1.13 on 2021-11-27 14:02

from django.db import migrations, models
import django.db.models.deletion
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211124_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(validators=[video_downloading_platform.core.models._validate_urls])),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='download_report',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.downloadreport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
