# Generated by Django 3.1.13 on 2021-11-27 15:26

from django.db import migrations, models
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211127_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedcontent',
            name='content',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=video_downloading_platform.core.models._get_upload_dir),
        ),
    ]
