# Generated by Django 3.1.13 on 2021-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211127_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='mime_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
