# Generated by Django 3.1.13 on 2021-12-05 12:04

from django.db import migrations, models
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211130_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadreport',
            name='archive',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=video_downloading_platform.core.models._get_zip_upload_dir),
        ),
    ]
