# Generated by Django 3.1.13 on 2022-01-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211207_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(default='No description', help_text='Add more details about the project here.'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(default='', help_text='Give a meaningful name to your collection. We suggest the name of your project, date, your initials separated by underscores. For example Ariha_Syria_20_Nov_2022_GI.', max_length=512, verbose_name='name'),
        ),
    ]
