# Generated by Django 3.1.13 on 2022-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220128_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='description',
            field=models.TextField(default='No description', help_text='Add more details about the project here.'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('GALLERY', 'Gallery')], default='VIDEO', editable=False, max_length=16),
        ),
    ]
