# Generated by Django 3.1.13 on 2022-04-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220415_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedcontent',
            name='description',
            field=models.TextField(blank=True, default='No description', help_text='Add more details about this file.', null=True),
        ),
    ]
