# Generated by Django 3.1.13 on 2022-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220415_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='exif_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='type',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('VIDEO', 'Video'), ('GALLERY', 'Gallery')], default='VIDEO', editable=False, max_length=16),
        ),
    ]
