# Generated by Django 3.1.13 on 2022-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220415_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
