# Generated by Django 3.1.13 on 2022-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_downloadedcontent_md5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadedcontent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='downloadreport',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='downloadrequest',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='target_file',
            field=models.BooleanField(default=False),
        ),
    ]
