# Generated by Django 3.1.13 on 2022-05-16 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_batch_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='contributors',
        ),
        migrations.CreateModel(
            name='BatchTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributors', models.ManyToManyField(help_text='List of contributors', related_name='shared_batches', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batchteam'),
        ),
    ]
