# Generated by Django 3.1.13 on 2022-08-24 14:11

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('core', '0027_auto_20220620_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='content_warning',
            field=models.TextField(blank=True, default='No warning', help_text='Add a content warning.', null=True),
        ),
        migrations.AddField(
            model_name='downloadedcontent',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
