# Generated by Django 3.1.13 on 2022-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220824_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='content_warning',
            field=models.TextField(blank=True, default='No warning', help_text='Add a content warning.', null=True),
        ),
    ]
