# Generated by Django 3.1.13 on 2022-08-29 14:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('core', '0029_downloadrequest_content_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedcontent',
            name='content_warning',
        ),
        migrations.RemoveField(
            model_name='downloadedcontent',
            name='tags',
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
