# Generated by Django 3.1.13 on 2022-08-29 15:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('core', '0030_auto_20220829_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
