# Generated by Django 3.1.13 on 2022-10-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20221026_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadrequest',
            old_name='start_addr',
            new_name='next_addr',
        ),
    ]
