# Generated by Django 3.1.13 on 2022-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20221026_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrequest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='sha1',
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='sha256',
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='CREATED', max_length=16),
        ),
    ]
