# Generated by Django 3.1.13 on 2022-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20221027_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedcontent',
            name='mime_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='downloadedcontent',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
