# Generated by Django 3.1.13 on 2022-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20221027_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='content_warning',
            field=models.TextField(blank=True, help_text='Add a content warning.', null=True),
        ),
    ]
