# Generated by Django 3.1.13 on 2022-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20221027_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
