# Generated by Django 3.1.13 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_batch_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='es_index',
            field=models.CharField(default='AzlnkepAeKd2funW', editable=False, max_length=16),
        ),
    ]
