# Generated by Django 3.1.13 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_batch_es_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='es_index',
            field=models.CharField(default='wtDbX47dCr8mGi38', editable=False, max_length=16),
        ),
    ]
