# Generated by Django 3.1.13 on 2023-05-05 10:42

from django.db import migrations, models
import video_downloading_platform.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20221122_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='es_index',
            field=models.CharField(default=video_downloading_platform.core.models._random_id_16, editable=False, max_length=16),
        ),
    ]
