# Generated by Django 3.1.13 on 2023-07-24 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230505_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('credentials', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
